name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Use the Ruby version required by your Jekyll site

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3b: Show installed gems (debugging step)
      - name: Show installed gems
        run: bundle show jekyll-theme-hacker

      # Step 4: Build the Jekyll site
      - name: Build the site
        run: bundle exec jekyll build

      # Step 5: Deploy to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
